#
# /etc/pacman.conf for AdvikOS (archiso)
#
[options]
HoldPkg     = pacman glibc
Architecture = auto

Color
CheckSpace
VerbosePkgLists
ParallelDownloads = 5

SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

# multilib is required for 32-bit Wine & legacy DirectX gaming
[multilib]
Include = /etc/pacman.d/mirrorlist

# Chaotic-AUR for prebuilt Waydroid binaries
[chaotic-aur]
SigLevel = Never
Server = https://geo-mirror.chaotic.cx/$repo/$arch
Server = https://cdn-mirror.chaotic.cx/$repo/$arch

